# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

EMERGE_DEFAULT_OPTS="--ask --verbose --keep-going --with-bdeps=y --jobs=4"
GENTOO_MIRRORS="https://mirrors.bfsu.edu.cn/gentoo"
GENTOO_MIRRORS="${GENTOO_MIRRORS} https://mirrors.tuna.tsinghua.edu.cn/gentoo"

FEATURES="ccache buildpkg"
CCACHE_DIR="/var/cache/ccache"
RUSTC_WRAPPER=/usr/bin/sccache
SCCACHE_DIR="/var/cache/sccache"
SCCACHE_MAX_FRAME_LENGTH=104857600
# ccache for c&c++, sccache for rust
# mkdir -p /var/cache/ccache /var/cache/sccache
# chown root:portage /var/cache/ccache /var/cache/sccache
# chmod 2775 /var/cache/ccache /var/cache/sccache
# /var/cache/ccache/ccache.conf
# max_size = 20.0G
# umask = 002
# compiler_check = %compiler% -v
# cache_dir_levels = 3

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C
L10N="en en-US zh zh-CN"

CHOST="x86_64-pc-linux-gnu"
MAKEOPTS="-j13"
CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3"

USE="cjk vaapi pulseaudio zstd"
MICROCODE_SIGNATURES="-S"
GRUB_PLATFORMS="efi-64"
INPUT_DEVICES="synaptics libinput wacom"
VIDEO_CARDS="intel i965 iris nouveau"

LLVM_TARGETS="X86"

ACCEPT_LICENSE="*"
# ACCEPT_KEYWORDS="~amd64"
# Use package.accept_keywords
# www-client/chromium official -suid
# app-i18n/fcitx5-configtool -kcm
# sys-devel/gcc -fortran
# net-libs/nodejs -npm
# font theme etc store at account home 

# world
# app-admin/eclean-kernel
# app-admin/stow
# app-admin/sudo
# app-arch/p7zip
# app-editors/neovim
# app-editors/vim
# app-eselect/eselect-repository
# app-i18n/fcitx5
# app-i18n/fcitx5-chinese-addons
# app-i18n/fcitx5-configtool
# app-i18n/fcitx5-gtk
# app-i18n/fcitx5-qt
# app-misc/neofetch
# app-misc/ranger
# app-portage/cpuid2cpuflags
# app-portage/eix
# app-portage/euses
# app-portage/flaggie
# app-portage/genlop
# app-portage/gentoolkit
# app-portage/portage-utils
# app-shells/bash-completion
# app-shells/gentoo-zsh-completions
# app-shells/zsh
# app-shells/zsh-completions
# app-text/highlight
# app-text/tree
# dev-lang/lua
# dev-python/pip
# dev-util/android-tools
# dev-util/ccache
# dev-util/ctags
# dev-util/dwarves
# dev-util/lldb
# dev-util/sccache
# dev-vcs/git
# lxde-base/lxappearance
# media-fonts/fantasque-sans-mono
# media-fonts/fira-code
# media-fonts/fontawesome
# media-fonts/noto
# media-fonts/noto-emoji
# media-fonts/terminus-font
# media-gfx/feh
# media-sound/pulseaudio
# media-sound/pulseaudio-modules-bt
# media-sound/pulsemixer
# media-video/mpv
# net-libs/nodejs
# net-misc/dhcpcd
# net-misc/proxychains
# net-wireless/bluez
# net-wireless/iwd
# sys-apps/exa
# sys-apps/man-db
# sys-apps/mlocate
# sys-apps/yarn
# sys-boot/grub:2
# sys-boot/os-prober
# sys-devel/clang
# sys-devel/gdb
# sys-devel/lld
# sys-firmware/intel-microcode
# sys-fs/dosfstools
# sys-fs/exfat-utils
# sys-fs/xfsprogs
# sys-kernel/dracut
# sys-kernel/gentoo-kernel-bin
# sys-kernel/gentoo-sources
# sys-kernel/linux-firmware
# sys-power/acpid
# sys-power/acpilight
# sys-power/powertop
# sys-process/htop
# www-client/google-chrome
# x11-apps/xinit
# x11-apps/xrandr
# x11-apps/xsetroot
# x11-base/xorg-server
# x11-libs/libnotify
# x11-libs/libva-intel-media-driver
# x11-misc/dunst
# x11-misc/numlockx
# x11-misc/picom
# x11-misc/polybar
# x11-misc/qt5ct
# x11-misc/rofi
# x11-misc/slock
# x11-misc/sxhkd
# x11-misc/xdg-user-dirs
# x11-misc/xsel
# x11-terms/alacritty
# x11-terms/kitty
# x11-themes/adwaita-qt
# x11-themes/gtk-engines
# x11-themes/gtk-engines-adwaita
# x11-wm/bspwm
