#! /bin/sh

# Killall

numlockx &
fcitx5 > /dev/null 2>&1 &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config /dev/null --backend glx --vsync --experimental-backends &
feh --bg-fill ~/Pictures/f9f5923b365db4e0fdd0c77d18eaa757.jpg &
~/.config/polybar/launch.sh &
dunst -config ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8
bspc config normal_border_color     "#44475a"
bspc config active_border_color     "#bd93f9"
bspc config focused_border_color    "#ff79c6"
bspc config presel_feedback_color   "#6272a4"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

