#! /bin/sh

# Killall

numlockx &
fcitx5 > /dev/null 2>&1 &
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config /dev/null --experimental-backends --backend glx --vsync &
feh --bg-fill ~/Pictures/wallpaperflare.com_wallpaper.jpg &
~/.config/polybar/launch.sh &
dunst -config ~/.config/dunst/dunstrc &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

