[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
padding = { x = 0, y = 0 }
startup_mode = "Maximized"

[font]
normal = { family = "monospace", style = "Regular" }
size = 14.0

[env]
TERM = "xterm-256color"
